name = "lustre_animation"
version = "0.4.0"
description = "Animations for lustre, utilizing JS requestAnimationFrame and setTimeout"
target = "javascript"
licenses = ["MIT"]
repository = { type = "codeberg", user = "kero", repo = "lustre_animation" }
links = [
    { title = "Home Page", href = "https://git.chmeee.org/lustre_animation" },
]

[dependencies]
gleam_stdlib = ">= 0.59.0 and < 1.0.0"
lustre = "~> 4.0 or ~> 5.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
