name = "lustre_animation"
version = "0.3.1"
description = "Animations for lustre, utilizing JS requestAnimationFrame and setTimeout"
target = "javascript"
licenses = ["MIT"]
repository = { type = "custom", url = "https://git.chmeee.org/lustre_animation" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
lustre = "~> 3.0 or ~> 4.0"

[dev-dependencies]
gleeunit = "~> 1.0"
